### ISSUE TITLE
NoClassDefFoundError: org/assertj/core/util/SystemProperties

### ISSUE THREAD

**Issue by jschneider** [joel-costigliola/assertj-swing#165]
I get this exception when using assertj-swing 2.1.1 with Maven:
Any ideas why that dependency is missing?

2015-09-23 08:49:54 INFO   [de.avat.service.ui.exception.ExceptionHandler uncaughtException] Handling Exception
java.lang.NoClassDefFoundError: org/assertj/core/util/SystemProperties
	at org.assertj.swing.core.BasicComponentFinder.componentNotFound(BasicComponentFinder.java:285)
	at org.assertj.swing.core.BasicComponentFinder.find(BasicComponentFinder.java:273)
	at org.assertj.swing.core.BasicComponentFinder.find(BasicComponentFinder.java:266)
	at org.assertj.swing.core.BasicComponentFinder.findByName(BasicComponentFinder.java:201)
	at org.assertj.swing.fixture.AbstractContainerFixture.findByName(AbstractContainerFixture.java:622)
	at org.assertj.swing.fixture.AbstractContainerFixture.textBox(AbstractContainerFixture.java:541)
[...]
	at de.avat.service.ui.actions.StartAutoNavigationAction.lambda$null$0(StartAutoNavigationAction.java:60)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.assertj.core.util.SystemProperties
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 16 more

**Comment by jschneider** [comment]
Okay, found it. Seems to be a duplicate of #161
