### ISSUE TITLE
Clicking on disabled Swing components

### ISSUE THREAD

**Issue by aguelle** [joel-costigliola/assertj-swing#169]
I have a disabled JTable that provides a popup menu:

    public class DisabledTableFrame extends JFrame {

    public DisabledTableFrame() {

        setSize(200, 100);
        setTitle(getClass().getCanonicalName());
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        JTable table = new JTable();
        add(table);

        table.addMouseListener(new MouseAdapter() {

            @Override
            public void mousePressed(MouseEvent e) {
                mouseReleased(e);
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                new PopupMenu();
            }

        });

        table.setEnabled(false);
        setVisible(true);
    }

    public static void main(String[] args) {
        new DisabledTableFrame();

    }

    private class PopupMenu extends JPopupMenu {

        public PopupMenu() {

            JMenuItem menuItem = new JMenuItem("TEST");
            add(menuItem);
            setVisible(true);
        }
    }
    }

I need to open the popup menu when the table is disabled and click a menu item. Unfortunately the ComponentPreconditions.checkEnabled() function throws an IllegalStateException when trying this with AssertJ swing. However you can see that opening a popup menu on a disabled component is a valid action in Swing.

**Comment by croesch** [comment]
Part of 3.1.1.

**Comment by aguelle** [comment]
Unfortunately this is not solved. Clicking on disabled components still does not work.

```
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;

import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JTable;

import org.assertj.swing.data.TableCell;
import org.assertj.swing.edt.GuiActionRunner;
import org.assertj.swing.edt.GuiQuery;
import org.assertj.swing.fixture.FrameFixture;
import org.assertj.swing.junit.testcase.AssertJSwingJUnitTestCase;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;

/**
 * Test for <a
 * href="https://github.com/joel-costigliola/assertj-swing/issues/169"
 * >github.com - assertj-swing #169</a>
 */
public class GitHub_169_DisabledComponentTest extends AssertJSwingJUnitTestCase {

	@Rule
	public TemporaryFolder temporaryFolder = new TemporaryFolder();

	protected FrameFixture window;

	@Override
	protected void onSetUp() {
		DisabledTableFrame mainFrame = GuiActionRunner
				.execute(new GuiQuery<DisabledTableFrame>() {

					protected DisabledTableFrame executeInEDT() {

						return new DisabledTableFrame();
					}
				});

		window = new FrameFixture(robot(), mainFrame);
	}

	@Test
	public void openPopupMenu() throws IOException {
		window.table().showPopupMenuAt(TableCell.row(0).column(0));
	}

	class DisabledTableFrame extends JFrame {

		public DisabledTableFrame() {

			setSize(200, 100);
			setTitle(getClass().getCanonicalName());
			setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
			JTable table = new JTable();
			add(table);

			table.addMouseListener(new MouseAdapter() {

				@Override
				public void mousePressed(MouseEvent e) {
					mouseReleased(e);
				}

				@Override
				public void mouseReleased(MouseEvent e) {
					new PopupMenu();
				}

			});

			table.setEnabled(false);
			setVisible(true);
		}
	}

	class PopupMenu extends JPopupMenu {

		public PopupMenu() {

			JMenuItem menuItem = new JMenuItem("TEST");
			add(menuItem);
			setVisible(true);
		}
	}
}
```
Results in:

```
java.lang.IllegalStateException: Expecting component javax.swing.JTable[name=null, rowCount=0, columnCount=0, enabled=false, visible=true, showing=true] to be enabled
	at org.assertj.swing.driver.ComponentPreconditions.checkEnabled(ComponentPreconditions.java:66)
	at org.assertj.swing.driver.ComponentPreconditions.checkEnabledAndShowing(ComponentPreconditions.java:46)
	at org.assertj.swing.driver.JTableDriver.scrollToCell(JTableDriver.java:503)
	at org.assertj.swing.driver.JTableDriver.lambda$8(JTableDriver.java:495)
	at org.assertj.swing.edt.GuiActionRunner$1.executeInEDT(GuiActionRunner.java:75)
	at org.assertj.swing.edt.GuiQuery.run(GuiQuery.java:42)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
	at org.assertj.swing.edt.GuiActionRunner.execute(GuiActionRunner.java:98)
	at org.assertj.swing.edt.GuiActionRunner.execute(GuiActionRunner.java:72)
	at org.assertj.swing.driver.JTableDriver.scrollToPointAtCell(JTableDriver.java:494)
	at org.assertj.swing.driver.JTableDriver.showPopupMenuAt(JTableDriver.java:486)
	at org.assertj.swing.fixture.JTableFixture.showPopupMenuAt(JTableFixture.java:602)
	at GitHub_169_DisabledComponentTest.openPopupMenu(GitHub_169_DisabledComponentTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**Comment by croesch** [comment]
Thanks for pointing me to this method. Probably not the last place where to insert the new behaviour.

**Comment by croesch** [comment]
Latest fix is contained in 3.6.0

**Comment by aguelle** [comment]
Unfortunately that does not work on my Mac. Have you tested with the code above on Windows?

**Comment by croesch** [comment]
Nope, just on Linux.
