### ISSUE TITLE
Showing popup on Linux with xvfb raises an exception

### ISSUE THREAD

**Issue by baudren** [joel-costigliola/assertj-swing#171]
I have a set of tests that behave differently locally (on a Win7) and remotely (on a CentOS, headless, using xvfb to capture screenshots).

Most interaction seem to work just fine, but the `showPopupMenu` method systematically throws a `ComponentLookupException` (see an example below), whether I try to simulate a right click on a table's header, or a line, or any other object.

From the stacktrace, it does not seem to be a matter of running out of screenspace and not being able to physically click on the item, either.

~~~ java
org.assertj.swing.exception.ComponentLookupException: Unable to show popup at java.awt.Point[x=29,y=22] on javax.swing.table.JTableHeader[,0,0,418x44,alignmentX=0.0,alignmentY=0.0,border=,flags=16777544,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=118,height=44],draggedDistance=0,reorderingAllowed=false,resizingAllowed=true,updateTableInRealTime=true]
	at org.assertj.swing.core.BasicRobot.showPopupMenu(BasicRobot.java:815)
	at org.assertj.swing.driver.JTableHeaderDriver.showPopupMenu(JTableHeaderDriver.java:186)
	at org.assertj.swing.fixture.JTableHeaderFixture.showPopupMenuAt(JTableHeaderFixture.java:168)
              .....
~~~

Since this popup menus play an important role in the application, I would really hope that it is not a limitation of using `xvfb`. Did any of you experience such a thing, or has a clue towards a solution?

Thanks in advance - and thanks for maintaining such an (otherwise :)) very reliable testing tool.

**Comment by baudren** [comment]
Just for reference - the problem was on the code side. We were testing the right-click action only in a `onReleased` event, not `onPressed`, with the method `isPopupTrigger`, which behaves differently on Windows and Linux. Fixing this solved the problem, which was not at all on assertj-swing side.
