### ISSUE TITLE
NPE on invoking JFrames with tray within AssertJSwingJUnitTestCase

### ISSUE THREAD

**Issue by angeloBerlin** [joel-costigliola/assertj-swing#197]
Running the test results in an NPE. Doing the same without extending AssertJSwingJUnitTestCase works fine.

```
import java.awt.AWTException;
import java.awt.Image;
import java.awt.SystemTray;
import java.awt.Toolkit;
import java.awt.TrayIcon;

import javax.swing.JFrame;

public class TrayFrame extends JFrame {

	public TrayFrame() {

		setSize(200, 100);

		if (SystemTray.isSupported()) {

			SystemTray tray = SystemTray.getSystemTray();
			Image image = Toolkit.getDefaultToolkit().getImage("");
			TrayIcon trayIcon = new TrayIcon(image);

			try {
				tray.add(trayIcon);
			} catch (AWTException e) {
				e.printStackTrace();
			}
		}

		setVisible(true);
	}

	public static void main(String[] args) {
		new TrayFrame();
	}
}
```

```
import org.assertj.swing.edt.GuiActionRunner;
import org.assertj.swing.edt.GuiQuery;
import org.assertj.swing.junit.testcase.AssertJSwingJUnitTestCase;
import org.junit.Test;

public class TrayTest extends AssertJSwingJUnitTestCase {

	@Override
	protected void onSetUp() {
	}

	@Test
	public void openFrameWithGuiRunner() {
		GuiActionRunner.execute(new GuiQuery<TrayFrame>() {

			@Override
			protected TrayFrame executeInEDT() {
				return new TrayFrame();
			}
		});
	}
}
```

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.assertj.core.util.Preconditions.checkNotNull(Preconditions.java:76)
	at org.assertj.swing.input.InputState.screenLocation(InputState.java:129)
	at org.assertj.swing.input.InputState.update(InputState.java:112)
	at org.assertj.swing.input.InputState$1.processEvent(InputState.java:72)
	at org.assertj.swing.listener.EventDispatchThreadedEventListener.eventDispatched(EventDispatchThreadedEventListener.java:79)
	at org.assertj.swing.input.EventNormalizer.delegate(EventNormalizer.java:92)
	at org.assertj.swing.input.EventNormalizer.eventDispatched(EventNormalizer.java:87)
	at org.assertj.swing.listener.WeakEventListener.eventDispatched(WeakEventListener.java:82)
	at java.awt.Toolkit$SelectiveAWTEventListener.eventDispatched(Toolkit.java:2425)
	at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2317)
	at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2316)
	at java.awt.Toolkit.notifyAWTEventListeners(Toolkit.java:2275)
	at java.awt.TrayIcon.dispatchEvent(TrayIcon.java:721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:763)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by croesch** [comment]
On which system and version are you runngin?

Using the latest AssertJ Swing under Linux works well for me. I copied your test and it runs normally - no exception, no test failures.

**Comment by aguelle** [comment]
Its running fine on MacOS but fails on Windows 10

**Comment by croesch** [comment]
Thx for the quick answer

**Comment by bernardobreder** [comment]
I have the same problem in my project and i have no idea how to solve.

[Server Process]: Sistema Operacional: Windows 10 10.0
[Server Process]: Timezone: sun.util.calendar.ZoneInfo[id="GMT-03:00",offset=-10800000,dstSavings=0,useDaylight=false,transitions=0,lastRule=null]
[Server Process]: JVM: 1.8.0_131
[Server Process]: Exceção: 
[Server Process]: Tipo: java.lang.NullPointerException
[Server Process]: Mensagem: null
[Server Process]: Pilha de execução:
[Server Process]: java.lang.NullPointerException
[Server Process]: 	at org.assertj.core.util.Preconditions.checkNotNull(Preconditions.java:76)
[Server Process]: 	at org.assertj.swing.input.InputState.screenLocation(InputState.java:129)
[Server Process]: 	at org.assertj.swing.input.InputState.update(InputState.java:112)
[Server Process]: 	at org.assertj.swing.input.InputState$1.processEvent(InputState.java:72)
[Server Process]: 	at org.assertj.swing.listener.EventDispatchThreadedEventListener.eventDispatched(EventDispatchThreadedEventListener.java:79)
[Server Process]: 	at org.assertj.swing.input.EventNormalizer.delegate(EventNormalizer.java:92)
[Server Process]: 	at org.assertj.swing.input.EventNormalizer.eventDispatched(EventNormalizer.java:87)
[Server Process]: 	at org.assertj.swing.listener.WeakEventListener.eventDispatched(WeakEventListener.java:82)
[Server Process]: 	at java.awt.Toolkit$SelectiveAWTEventListener.eventDispatched(Toolkit.java:2425)
[Server Process]: 	at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2317)
[Server Process]: 	at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2316)
[Server Process]: 	at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2316)
[Server Process]: 	at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2316)
[Server Process]: 	at java.awt.Toolkit.notifyAWTEventListeners(Toolkit.java:2275)
[Server Process]: 	at java.awt.TrayIcon.dispatchEvent(TrayIcon.java:721)
[Server Process]: 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:763)
[Server Process]: 	at java.awt.EventQueue.access$500(EventQueue.java:97)
[Server Process]: 	at java.awt.EventQueue$3.run(EventQueue.java:709)
[Server Process]: 	at java.awt.EventQueue$3.run(EventQueue.java:703)
[Server Process]: 	at java.security.AccessController.doPrivileged(Native Method)
[Server Process]: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
[Server Process]: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
[Server Process]: 	at java.awt.EventQueue$4.run(EventQueue.java:731)
[Server Process]: 	at java.awt.EventQueue$4.run(EventQueue.java:729)
[Server Process]: 	at java.security.AccessController.doPrivileged(Native Method)
[Server Process]: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
[Server Process]: 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
[Server Process]: 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
[Server Process]: 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
[Server Process]: 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
[Server Process]: 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[Server Process]: 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
[Server Process]: 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by subes** [comment]
Here my go at the problem.

**Comment by croesch** [comment]
Thanks very much!
