### ISSUE TITLE
BasicRobot issue in assertj-core-3.8.0

### ISSUE THREAD

**Issue by michaellynott** [joel-costigliola/assertj-swing#218]
On Windows 10 (v 1703) under Eclipse Oxygen 4.7.1a and Java JRE 1.8_0_151 I ran the following short program, which runs under assert-core-1.7.1 and faults under assert-swing-3.8.0. 

package testrobotpkg;
import org.assertj.swing.core.BasicRobot;
import org.assertj.swing.core.Robot;

public class TestRobotClass {

	public static void main(String[] args) {
		Robot robot= null;
		System.out.println("Before call to BasicRobot");
		robot = BasicRobot.robotWithNewAwtHierarchy();
		System.out.println("After call to BasicRobot");
		robot = null;
	}

}

Output when run with assertj-core-3.8.0 and assertj-swing-1.2.0

Before call to BasicRobot
Exception in thread "main" java.lang.NoSuchMethodError: org.assertj.core.util.Maps.newWeakHashMap()Ljava/util/WeakHashMap;
	at org.assertj.swing.edt.GuiActionRunner.rethrowCaughtExceptionIn(GuiActionRunner.java:154)
	at org.assertj.swing.edt.GuiActionRunner.resultOf(GuiActionRunner.java:132)
	at org.assertj.swing.edt.GuiActionRunner.execute(GuiActionRunner.java:77)
	at org.assertj.swing.monitor.WindowMonitor$SingletonLazyLoader.<clinit>(WindowMonitor.java:150)
	at org.assertj.swing.monitor.WindowMonitor.instance(WindowMonitor.java:145)
	at org.assertj.swing.core.BasicRobot.<clinit>(BasicRobot.java:120)
	at testrobotpkg.TestRobotClass.main(TestRobotClass.java:13)
	
Output when run with assertj-core-1.7.1 and assertj-swing-1.2.0
Before call to BasicRobot
After call to BasicRobot

**Comment by bigkahuna1uk** [comment]
Looks like Maps.newWeakHashMap has been removed from assertj 3.8.0+. only hashmap now exists.

**Comment by croesch** [comment]
Please make sure to run compatible versions of AssertJ Swing and AssertJ Core. AssertJ Swing 1.2.0 will certainly not run against AssertJ Core 3.8.0 - use AssertJ Swing 3.7.0 for this purpose. Have a look at [this page](https://joel-costigliola.github.io/assertj/assertj-swing-news.html).
