### ISSUE TITLE
Asertj-swing seems not work well on windows 10

### ISSUE THREAD

**Issue by zenddup** [joel-costigliola/assertj-swing#222]
Hi,
when I run test testcase under windows 10, it cann't click on the main menus,but on the title bar.
How to make it click on the right menu bar on windows 10?

my test codes is as follows:
```
import org.assertj.swing.fixture.FrameFixture;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import javax.swing.JFrame;
import org.assertj.swing.edt.GuiActionRunner;
import org.assertj.swing.junit.testcase.AssertJSwingJUnitTestCase;


/**
 *
 */
public class SsmpleFrameTestAssertJ extends AssertJSwingJUnitTestCase{

    private FrameFixture mFrame;

    public SsmpleFrameTestAssertJ(){
    }

    @Before
    public void onSetUp(){
    	SampleFrame2 frame = GuiActionRunner.execute(() -> new SampleFrame2());
    	frame.setExtendedState(JFrame.MAXIMIZED_BOTH); 
    	mFrame = new FrameFixture(robot(), frame);
    	mFrame.show();
           
    }

    @After
    public void onTearDown(){
        cleanUp();
    }

    @Test
    public void testMenu(){
        //mFrame.menuItemWithPath( "File", "exit" ).click();
        mFrame.menuItem("File").click();

    }
}
```

the SampleFrame2 is just a simple simple with main menu [file],
the exception is ：

```
org.assertj.swing.exception.ComponentLookupException: Unable to find component using matcher org.assertj.swing.core.NameMatcher[name='File', type=javax.swing.JMenuItem, requireShowing=false].

Component hierarchy:
jp.navalvessel.demo.SampleFrame2[name='frame0', title='', enabled=true, visible=true, showing=true]
  javax.swing.JRootPane[]
    javax.swing.JPanel[name='null.glassPane']
    javax.swing.JLayeredPane[]
      javax.swing.JPanel[name='null.contentPane']
        javax.swing.JCheckBox[name='check2', text='CheckBox2', selected=false, enabled=true, visible=true, showing=true]
        javax.swing.JRadioButton[name='radio2', text='RadioButton2', selected=false, enabled=true, visible=true, showing=true]
        javax.swing.JCheckBox[name='check3', text='CheckBox3', selected=false, enabled=true, visible=true, showing=true]
        javax.swing.JRadioButton[name='radio3', text='RadioButton3', selected=false, enabled=true, visible=true, showing=true]
        javax.swing.JCheckBox[name='check1', text='CheckBox1', selected=false, enabled=true, visible=true, showing=true]
        javax.swing.JRadioButton[name='radio1', text='RadioButton1', selected=true, enabled=true, visible=true, showing=true]
        javax.swing.JButton[name='showOptionPane', text='showOptionPane', enabled=true, visible=true, showing=true]
        javax.swing.JTabbedPane[name='tabPane', selectedTabIndex=0, selectedTabTitle='tab1', tabCount=3, tabTitles=["tab1", "tab2", "tab3"], enabled=true, visible=true, showing=true
          javax.swing.JScrollPane[name=null, enabled=true, visible=true, showing=true]
            javax.swing.JViewport[,1,1,1912x731,layout=javax.swing.ViewportLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=25165832,maximumSize=,minimumSize=,preferredSize=,isViewSizeSet=true,lastPaintPosition=java.awt.Point[x=0,y=0],scrollUnderway=false]
              javax.swing.JTextArea[name=null, text='', enabled=true, visible=true, showing=true]
            javax.swing.JScrollPane$ScrollBar[name=null, value=0, blockIncrement=10, minimum=0, maximum=731, enabled=true, visible=false, showing=false]
              javax.swing.plaf.metal.MetalScrollButton[name=null, text='', enabled=true, visible=true, showing=false]
              javax.swing.plaf.metal.MetalScrollButton[name=null, text='', enabled=true, visible=true, showing=false]
            javax.swing.JScrollPane$ScrollBar[name=null, value=0, blockIncrement=10, minimum=0, maximum=1912, enabled=true, visible=false, showing=false]
              javax.swing.plaf.metal.MetalScrollButton[name=null, text='', enabled=true, visible=true, showing=false]
              javax.swing.plaf.metal.MetalScrollButton[name=null, text='', enabled=true, visible=true, showing=false]
          javax.swing.JScrollPane[name=null, enabled=true, visible=false, showing=false]
            javax.swing.JViewport[,1,1,1912x731,layout=javax.swing.ViewportLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=25165832,maximumSize=,minimumSize=,preferredSize=,isViewSizeSet=true,lastPaintPosition=,scrollUnderway=false]
              javax.swing.JTextArea[name=null, text='', enabled=true, visible=true, showing=false]
            javax.swing.JScrollPane$ScrollBar[name=null, value=0, blockIncrement=10, minimum=0, maximum=731, enabled=true, visible=false, showing=false]
              javax.swing.plaf.metal.MetalScrollButton[name=null, text='', enabled=true, visible=true, showing=false]
              javax.swing.plaf.metal.MetalScrollButton[name=null, text='', enabled=true, visible=true, showing=false]
            javax.swing.JScrollPane$ScrollBar[name=null, value=0, blockIncrement=10, minimum=0, maximum=1912, enabled=true, visible=false, showing=false]
              javax.swing.plaf.metal.MetalScrollButton[name=null, text='', enabled=true, visible=true, showing=false]
              javax.swing.plaf.metal.MetalScrollButton[name=null, text='', enabled=true, visible=true, showing=false]
          javax.swing.JScrollPane[name=null, enabled=true, visible=false, showing=false]
            javax.swing.JViewport[,1,1,1912x731,layout=javax.swing.ViewportLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=25165832,maximumSize=,minimumSize=,preferredSize=,isViewSizeSet=true,lastPaintPosition=,scrollUnderway=false]
              javax.swing.JTextArea[name=null, text='', enabled=true, visible=true, showing=false]
            javax.swing.JScrollPane$ScrollBar[name=null, value=0, blockIncrement=10, minimum=0, maximum=731, enabled=true, visible=false, showing=false]
              javax.swing.plaf.metal.MetalScrollButton[name=null, text='', enabled=true, visible=true, showing=false]
              javax.swing.plaf.metal.MetalScrollButton[name=null, text='', enabled=true, visible=true, showing=false]
            javax.swing.JScrollPane$ScrollBar[name=null, value=0, blockIncrement=10, minimum=0, maximum=1912, enabled=true, visible=false, showing=false]
              javax.swing.plaf.metal.MetalScrollButton[name=null, text='', enabled=true, visible=true, showing=false]
              javax.swing.plaf.metal.MetalScrollButton[name=null, text='', enabled=true, visible=true, showing=false]
        javax.swing.JScrollPane[name=null, enabled=true, visible=true, showing=true]
          javax.swing.JViewport[,1,21,1893x95,layout=javax.swing.ViewportLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=25165832,maximumSize=,minimumSize=,preferredSize=,isViewSizeSet=true,lastPaintPosition=java.awt.Point[x=0,y=0],scrollUnderway=false]
            javax.swing.JTable[name='table', rowCount=4, columnCount=4, enabled=true, visible=true, showing=true]
              javax.swing.CellRendererPane[,0,0,0x0,hidden]
          javax.swing.JScrollPane$ScrollBar[name=null, value=0, blockIncrement=10, minimum=0, maximum=64, enabled=true, visible=false, showing=false]
            javax.swing.plaf.metal.MetalScrollButton[name=null, text='', enabled=true, visible=true, showing=false]
            javax.swing.plaf.metal.MetalScrollButton[name=null, text='', enabled=true, visible=true, showing=false]
          javax.swing.JScrollPane$ScrollBar[name=null, value=0, blockIncrement=10, minimum=0, maximum=1893, enabled=true, visible=false, showing=false]
            javax.swing.plaf.metal.MetalScrollButton[name=null, text='', enabled=true, visible=true, showing=false]
            javax.swing.plaf.metal.MetalScrollButton[name=null, text='', enabled=true, visible=true, showing=false]
          javax.swing.JViewport[,1,1,1893x20,layout=javax.swing.ViewportLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=25165832,maximumSize=,minimumSize=,preferredSize=,isViewSizeSet=true,lastPaintPosition=java.awt.Point[x=0,y=0],scrollUnderway=false]
            javax.swing.table.JTableHeader[,0,0,1893x20,alignmentX=0.0,alignmentY=0.0,border=,flags=16777544,maximumSize=,minimumSize=,preferredSize=,draggedDistance=0,reorderingAllowed=true,resizingAllowed=true,updateTableInRealTime=true]
              javax.swing.CellRendererPane[,0,0,0x0,hidden]
      javax.swing.JMenuBar[]
        javax.swing.JMenu[name=null, text='File', selected=false, enabled=true, visible=true, showing=true]
          javax.swing.JPopupMenu[name=null, label=null, enabled=true, visible=false, showing=false]
            javax.swing.JMenuItem[name=null, text='remove tab', selected=false, enabled=true, visible=true, showing=false]
            javax.swing.JMenuItem[name=null, text='exit', selected=false, enabled=true, visible=true, showing=false]
        javax.swing.JMenu[name=null, text='Edit', selected=false, enabled=true, visible=true, showing=true]
          javax.swing.JPopupMenu[name=null, label=null, enabled=true, visible=false, showing=false]

	at org.assertj.swing.core.BasicComponentFinder.componentNotFound(BasicComponentFinder.java:287)
	at org.assertj.swing.core.BasicComponentFinder.find(BasicComponentFinder.java:272)
	at org.assertj.swing.core.BasicComponentFinder.find(BasicComponentFinder.java:265)
	at org.assertj.swing.core.BasicComponentFinder.findByName(BasicComponentFinder.java:200)
	at org.assertj.swing.fixture.AbstractContainerFixture.menuItem(AbstractContainerFixture.java:339)
	at jp.navalvessel.demo.SsmpleFrameTestAssertJ.testMenu(SsmpleFrameTestAssertJ.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:73)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:46)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:180)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:41)
	at org.junit.runners.ParentRunner$1.evaluate(ParentRunner.java:173)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:220)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)
```
Thanks,
Johhny.

**Comment by croesch** [comment]
Hi Johhny,

thanks for the report. Your code looks like
```
mFrame.menuItem("File").click();
```
but
```
mFrame.menuItemWithPath( "File").click();
```
should work for you without changing the application itself. Because that would use the text instead of the name of the menu.

---

The test is looking for something with **name**`='File'`:
```
Unable to find component using matcher org.assertj.swing.core.NameMatcher[name='File',  [..]
```
however your component hierarchy has only a menu without name, but with **text**`='File'`:
```
javax.swing.JMenu[name=null, text='File', [..]
```

I suggest (instead of using the text of the menus) you give your menu items names and use that with your test code instead of `'File'`.

Please reopen the issue if any problem still exists or you have further questions - otherwise I assume the answer helped.
