### ISSUE TITLE
Illegalstate exception is thrown for an editable JComboBox

### ISSUE THREAD

**Issue by croesch** [joel-costigliola/assertj-swing#70]
_Issue by **[anita pillai](http://jira.codehaus.org/secure/ViewProfile.jspa?name=apillai)** from Thu, 24 Jun 2010 22:31:23 -0500_
_Originally opened as http://jira.codehaus.org/browse/FEST-366_

----

<p>    When I try to test my custom JComboBox I get an<br/>
IllegalStateException for a very specific situation.</p>

<p>Abt my code, I have added my custom comboBox to a dummy frame which is<br/>
then assigned to a FrameFixture for testing purposes. All my other<br/>
tests for this comboBox run successfully except when I set it to<br/>
editable and try to enter text.</p>

<p>This is the part of my code that fails:<br/>
...</p>

<p> comboBoxEditor.setEditable(true);<br/>
 dummyFrameFixture.comboBox("comboBoxEditor").enterText("some value");</p>

<p>When .enterText("some value"); is executed an illegalStateException is<br/>
thrown.</p>

<p>I dug into the fest code and the JComboBoxDriver's<br/>
enterText(JComboBox comboBox, String text)  method is called. In this<br/>
method a call is made to find the editor associated with the combobox<br/>
(note: I have not added any custom editors to my combobox) and call is<br/>
made to the focusAndWaitForFocusGain() method under ComponentDriver.<br/>
This method in turn calls assertIsEnabledAndShowing on the editor<br/>
which returns false because when the isShowing method under Component<br/>
class is called it returns false because its "peer" value has been set<br/>
to null.</p>

<p>I tried to replace my custom combo box with a dummy combo box and the<br/>
test executed without any issues. Any idea why this is happening and<br/>
what needs to be done?</p>

<p>Stack Trace:</p>

<p>java.lang.IllegalStateException: Expecting component<br/>
javax.swing.plaf.metal.MetalComboBoxEditor$1[name=null, text='',<br/>
enabled=true, visible=true, showing=false] to be showing on the screen<br/>
        at<br/>
org.fest.swing.driver.ComponentStateValidator.componentNotShowingOnScreenFailure(ComponentStateValidator.java:<br/>
87)<br/>
        at<br/>
org.fest.swing.driver.ComponentStateValidator.validateIsShowing(ComponentStateValidator.java:<br/>
72)<br/>
        at<br/>
org.fest.swing.driver.ComponentStateValidator.validateIsEnabledAndShowing(ComponentStateValidator.java:<br/>
44)<br/>
        at org.fest.swing.driver.ComponentDriver<br/>
$2.executeInEDT(ComponentDriver.java:499)<br/>
        at org.fest.swing.edt.GuiTask.run(GuiTask.java:37)<br/>
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)<br/>
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:597)<br/>
        at<br/>
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:<br/>
269)<br/>
        at<br/>
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:<br/>
184)<br/>
        at<br/>
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:<br/>
174)<br/>
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:<br/>
169)<br/>
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:<br/>
161)<br/>
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)<br/>
        at org.fest.swing.edt.GuiActionRunner.execute(GuiActionRunner.java:<br/>
97)<br/>
        at<br/>
org.fest.swing.driver.ComponentDriver.assertIsEnabledAndShowing(ComponentDriver.java:<br/>
497)<br/>
        at<br/>
org.fest.swing.driver.ComponentDriver.focusAndWaitForFocusGain(ComponentDriver.java:<br/>
362)<br/>
        at<br/>
org.fest.swing.driver.JComboBoxDriver.enterText(JComboBoxDriver.java:<br/>
370)<br/>
        at<br/>
org.fest.swing.fixture.JComboBoxFixture.enterText(JComboBoxFixture.java:<br/>
198)<br/>
        at<br/>
com.irise.studio.editor.ComboBoxEditorViewTest.testFireValueChangedOnEnterKeyInEditableMode(ComboBoxEditorViewTest.java:<br/>
256) </p>

----

votes (original issue): 0
watches (original issue): 0

**Comment by croesch** [comment]
Works fine for me. Cannot reproduce.
