### ISSUE TITLE
NPE right after test runs

### ISSUE THREAD

**Issue by croesch** [joel-costigliola/assertj-swing#73]
_Issue by **[AmbatiDev](http://jira.codehaus.org/secure/ViewProfile.jspa?name=ambati.dev)** from Fri, 6 Aug 2010 14:17:20 -0500_
_Originally opened as http://jira.codehaus.org/browse/FEST-379_

----

<p>I am getting following exception right after my test is executed. Any <br/>
ideas? <br/>
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException <br/>
at <br/>
org.fest.swing.monitor.WindowVisibilityMonitor.windowClosed(WindowVisibilit yMonitor.java: <br/>
52) <br/>
at java.awt.AWTEventMulticaster.windowClosed(AWTEventMulticaster.java: <br/>
343) <br/>
at java.awt.Window.processWindowEvent(Window.java:1865) <br/>
at javax.swing.JFrame.processWindowEvent(JFrame.java:279) <br/>
at java.awt.Window.processEvent(Window.java:1820) <br/>
at java.awt.Component.dispatchEventImpl(Component.java:4630) <br/>
at java.awt.Container.dispatchEventImpl(Container.java:2099) <br/>
at java.awt.Window.dispatchEventImpl(Window.java:2475) <br/>
at java.awt.Component.dispatchEvent(Component.java:4460) <br/>
at java.awt.EventQueue.dispatchEvent(EventQueue.java:599) <br/>
at <br/>
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.jav a: <br/>
269) <br/>
at <br/>
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java: <br/>
184) <br/>
at <br/>
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.jav a: <br/>
174) <br/>
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java: <br/>
169) <br/>
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java: <br/>
161) <br/>
at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)</p>

----

votes (original issue): 0
watches (original issue): 0

**Comment by croesch** [comment]
I assume a client code problem.
