### ISSUE TITLE
GuiTestRunner throws exception on headless machines

### ISSUE THREAD

**Issue by croesch** [joel-costigliola/assertj-swing#90]
_Issue by **[Carsten Behring](http://jira.codehaus.org/secure/ViewProfile.jspa?name=carsten.behring@efsa.europa.eu)** from Wed, 12 Oct 2011 14:57:18 -0500_
_Originally opened as http://jira.codehaus.org/browse/FEST-452_

----

<p>I develop some tests with fest swing, and I want that my tests run on my local linux PC, but get skipped on a headless CI server.</p>

<p>I get the skipping of the tests easely working by doing a Junit Rule, which checks for the headless property "java.awt.headless" and then skips the test.</p>

<p>If I know annotate my test class with @GuiTestRunner (in order to get screenshots), the test suite fails now in headless mode with:<br/>
org.fest.swing.image.ImageException: Unable to create AWT Robot<br/>
	at org.fest.swing.image.ScreenshotTaker.&lt;init&gt;(ScreenshotTaker.java:69)<br/>
	at org.fest.swing.image.ScreenshotTaker.&lt;init&gt;(ScreenshotTaker.java:60)<br/>
	at org.fest.swing.junit.runner.FailureScreenshotTaker.&lt;init&gt;(FailureScreenshotTaker.java:46)<br/>
	at org.fest.swing.junit.v4_5.runner.GUITestRunner.&lt;init&gt;(GUITestRunner.java:39)<br/>
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)<br/>
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)<br/>
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)<br/>
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)<br/>
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:31)<br/>
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:24)<br/>
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:57)<br/>
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:29)<br/>
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:57)<br/>
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:24)<br/>
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:38)<br/>
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:199)<br/>
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:62)<br/>
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)<br/>
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)<br/>
Caused by: java.awt.AWTException: headless environment<br/>
	at java.awt.Robot.&lt;init&gt;(Robot.java:75)<br/>
	at org.fest.swing.util.RobotFactory.newRobotInPrimaryScreen(RobotFactory.java:35)<br/>
	at org.fest.swing.image.ScreenshotTaker.&lt;init&gt;(ScreenshotTaker.java:67)<br/>
	... 21 more</p>

<p>This is because the GuiTestRunner tries to call "new Robot()" in the constructor (which the throws an Exception)</p>

<p>It would be better, if the GuiTestRunner in this cases would just "continue" a only at the time of the scrennshot either </p>

<p>1) fails with exception (this would work for me, as I kip tests anzwaz in headless mode)</p>

<p>OR</p>

<p>2) just not do the screenshot (mazbe printing a message on the screen)</p>

<p>I did my own GuiTestRunner class, which basically does this. It catches and ignores exceptions in the constructor (ugly ...),<br/>
but working for me.</p>

----

votes (original issue): 0
watches (original issue): 0

**Comment by croesch** [comment]
Thanks @behrica for the patch and sorry for the delay :)
